const allMovies = [ {
		id: 1,
		// image: image1,
		title: "Avatar",
		age: "+13",
		tags: "Vtipný * Napínavý * Rodina",
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
	}, {
		id: 2,
		// image: image2,
		title: "Avatar 2",
		age: "+13",
		tags: "Vtipný * Napínavý * Rodina",
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
	}, {
		id: 3,
		// image: image3,
		title: "Rocknrolla",
		age: "+16",
		tags: "Gangster * Napínavý * Násilí",
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
	}, {
		id: 4,
		// image: image4,
		title: "Patriot",
		age: "+16",
		tags: "Gangster * Napínavý * Násilí",
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
	}, {
		id: 5,
		// image: image5,
		title: "Telefon pana Harrigana",
		age: "+16",
		tags: "Gangster * Napínavý * Násilí",
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
	}, {
		id: 6,
		// image: image6,
		title: "Stážista",
		age: "+16",
		tags: "Rodinný * Napínavý * Romantický",
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
	}, {
		id: 7,
		// image: image7,
		title: "Život",
		age: "+13",
		tags: "Vesmír * Napínavý * Nebezpečí",
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
	}, {
		id: 8,
		// image: image8,
		title: "Kód za miliardu dolarů",
		age: "+13",
		tags: "IT * Napínavý",
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
	}, {
		id: 9,
		// image: image9,
		title: "Pracháči",
		age: "+16",
		tags: "Dokument * Napínavý",
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
	}, {
		id: 10,
		// image: image10,
		title: "Whoami",
		age: "+13",
		tags: "Gangster * Napínavý * Násilí",
		description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
	},
]
export default allMovies